export const carManufacturers = [
    "Toyota",
    "Honda",
    "Ford",
    "Chevrolet",
    "Volkswagen",
    "BMW",
    "Mercedes-Benz",
    "Audi",
    "Nissan",
    "Tesla",
    "Hyundai",
    "Kia",
    "Subaru",
    "Mazda",
    "Lexus",
    "Volvo",
    "Porsche",
    "Land Rover",
    "Jaguar",
    "Ferrari",
    "Lamborghini",
    "Maserati",
    "Bentley",
    "Rolls-Royce",
    "Aston Martin",
    "Bugatti",
    "McLaren",
    "Alfa Romeo",
    "Jeep",
    "Chrysler",
    "Dodge",
    "Ram",
    "GMC",
    "Cadillac",
    "Lincoln",
    "Buick",
    "Acura",
    "Infiniti",
    "Genesis",
    "Smart",
    "Suzuki",
    "Mini",
    "Fiat",
    "Mitsubishi",
    "Peugeot",
    "Renault",
    "Citroën",
    "Skoda",
    "Seat",
    "Opel",
    "Vauxhall"
  ];
  