export const carManufacturers = [
    "Toyota",
    "Honda",
    "Ford",
    "Chevrolet",
    "Volkswagen",
    "BMW",
    "Mercedes-Benz",
    "Audi",
    "Nissan",
    "Tesla",
    "Hyundai",
    "Kia",
    "Subaru",
    "Mazda",
    "Lexus",
    "Volvo",
    "Porsche",
    "Land Rover",
    "Jaguar",
    "Ferrari",
    "Lamborghini",
    "Maserati",
    "Bentley",
    "Rolls-Royce",
    "Aston Martin",
    "Bugatti",
    "McLaren",
    "Alfa Romeo",
    "Jeep",
    "Chrysler",
    "Dodge",
    "Ram",
    "GMC",
    "Cadillac",
    "Lincoln",
    "Buick",
    "Acura",
    "Infiniti",
    "Genesis",
    "Smart",
    "Suzuki",
    "Mini",
    "Fiat",
    "Mitsubishi",
    "Peugeot",
    "Renault",
    "Citroën",
    "Skoda",
    "Seat",
    "Opel",
    "Vauxhall"
  ];

export const footerLinks = [
    {
      title: "About",
      links: [
        { title: "How it works", url: "/" },
        { title: "Featured", url: "/" },
        { title: "Partnership", url: "/" },
        { title: "Bussiness Relation", url: "/" },
      ],
    },
    {
      title: "Company",
      links: [
        { title: "Events", url: "/" },
        { title: "Blog", url: "/" },
        { title: "Podcast", url: "/" },
        { title: "Invite a friend", url: "/" },
      ],
    },
    {
      title: "Socials",
      links: [
        { title: "Discord", url: "/" },
        { title: "Instagram", url: "/" },
        { title: "Twitter", url: "/" },
        { title: "Facebook", url: "/" },
      ],
    },
  ];